-- Crear el usuario y otorgar permisos
CREATE USER colegio IDENTIFIED BY password;
GRANT CONNECT, RESOURCE TO colegio;

-- Utilizar el esquema
ALTER SESSION SET CURRENT_SCHEMA = colegio;

-- Crear la tabla alumno
CREATE TABLE alumno (
  id_alumno NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  nombres VARCHAR2(50) NOT NULL,
  apellidos VARCHAR2(50) NOT NULL,
  sexo CHAR(1) NOT NULL,
  estado NUMBER(1) NOT NULL,
  PRIMARY KEY (id_alumno)
);

-- Crear la tabla curso
CREATE TABLE curso (
  id_curso NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  descripcion VARCHAR2(50) NOT NULL,
  estado NUMBER(1) NOT NULL,
  PRIMARY KEY (id_curso)
);

-- Crear la tabla profesor
CREATE TABLE profesor (
  id_profesor NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  nombre VARCHAR2(50) NOT NULL,
  apellidos VARCHAR2(50) NOT NULL,
  sexo CHAR(1) NOT NULL,
  estado NUMBER(1) NOT NULL,
  PRIMARY KEY (id_profesor)
);

-- Crear la tabla alumno_curso
CREATE TABLE alumno_curso (
  cod_alumno NUMBER NOT NULL,
  cod_curso NUMBER NOT NULL,
  id_alumno_curso NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  PRIMARY KEY (id_alumno_curso),
  CONSTRAINT fk_cod_alu_alum_curso FOREIGN KEY (cod_alumno) REFERENCES alumno (id_alumno),
  CONSTRAINT fk_cod_cur_alum_curso FOREIGN KEY (cod_curso) REFERENCES curso (id_curso)
);

-- Crear la tabla curso_profesor
CREATE TABLE curso_profesor (
  cod_curso NUMBER NOT NULL,
  cod_profesor NUMBER NOT NULL,
  id_curso_profesor NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  PRIMARY KEY (id_curso_profesor),
  CONSTRAINT fk_cod_cur_curso_prof FOREIGN KEY (cod_curso) REFERENCES curso (id_curso),
  CONSTRAINT fk_cod_prof_curso_prof FOREIGN KEY (cod_profesor) REFERENCES profesor (id_profesor)
);

-- Insertar datos en la tabla alumno
INSERT INTO alumno (nombres, apellidos, sexo, estado)
VALUES ('Robert', 'Otiniano', 'M', 1);
INSERT INTO alumno (nombres, apellidos, sexo, estado)
VALUES ('Albert', 'Morales', 'M', 1);
INSERT INTO alumno (nombres, apellidos, sexo, estado)
VALUES ('Yeni', 'Mendoza', 'F', 1);
INSERT INTO alumno (nombres, apellidos, sexo, estado)
VALUES ('Alex', 'Mamaní', 'M', 1);
INSERT INTO alumno (nombres, apellidos, sexo, estado)
VALUES ('Bryan', 'Condor', 'M', 1);
INSERT INTO alumno (nombres, apellidos, sexo, estado)
VALUES ('TEST1', 'TEST2', 'F', 1);
INSERT INTO alumno (nombres, apellidos, sexo, estado)
VALUES ('TTT', 'TTT', 'F', 1);

-- Insertar datos en la tabla curso
INSERT INTO curso (descripcion, estado)
VALUES ('Análisis y Diseño', 1);
INSERT INTO curso (descripcion, estado)
VALUES ('Base de Datos', 1);
INSERT INTO curso (descripcion, estado)
VALUES ('Lenguaje de Programación', 1);
INSERT INTO curso (descripcion, estado)
VALUES ('Inteligencia Artificial', 1);

-- Insertar datos en la tabla profesor
INSERT INTO profesor (nombre, apellidos, sexo, estado)
VALUES ('Juan', 'Salazar', 'M', 1);
INSERT INTO profesor (nombre, apellidos, sexo, estado)
VALUES ('Jose', 'Atunga', 'M', 1);
INSERT INTO profesor (nombre, apellidos, sexo, estado)
VALUES ('Celso', 'Calla', 'M', 1);

-- Insertar datos en la tabla alumno_curso
INSERT INTO alumno_curso (cod_alumno, cod_curso)
VALUES (1, 2);
INSERT INTO alumno_curso (cod_alumno, cod_curso)
VALUES (2, 1);
INSERT INTO alumno_curso (cod_alumno, cod_curso)
VALUES (3, 4);
INSERT INTO alumno_curso (cod_alumno, cod_curso)
VALUES (4, 3);
INSERT INTO alumno_curso (cod_alumno, cod_curso)
VALUES (5, 1);

-- Insertar datos en la tabla curso_profesor
INSERT INTO curso_profesor (cod_curso, cod_profesor)
VALUES (1, 1);
INSERT INTO curso_profesor (cod_curso, cod_profesor)
VALUES (2, 2);
INSERT INTO curso_profesor (cod_curso, cod_profesor)
VALUES (3, 3);
INSERT INTO curso_profesor (cod_curso, cod_profesor)
VALUES (2, 1);
INSERT INTO curso_profesor (cod_curso, cod_profesor)
VALUES (4, 3);


select * from alumno;

use colegio;